public class DataFactory {
    
    public static Account insertAccount(){
        Account acc = new Account();
        acc.Name = 'Account Test';
        insert acc;
        return acc;
    }
    
    public static Contact insertContact(Account acc){
        Contact contc = new Contact();
        contc.FirstName = 'FistName Test';
        contc.LastName = 'LastName Test';
        contc.AccountId = acc.Id;
        contc.Email = 'test@test.com';
        insert contc;
        return contc;
    }
    
    public static FS_ProductoAdquirido__c insertProduct(Account acc, String prod, String mod, String subM){
        FS_ProductoAdquirido__c p = new FS_ProductoAdquirido__c();
        p.FS_Cuenta__c = acc.Id;
        p.FS_Producto__c = prod;
        p.FS_Modulo__c = mod;
        p.FS_SubModulo__c = subM;
        insert p;
        return p;
    }
    
    public static Case insertCase(Account acc, Contact cont, FS_ProductoAdquirido__c p, String tipoRegistro){
        Case caso = new Case();
        caso.AccountId = acc.Id;
        caso.ContactId = cont.Id;
        caso.FS_Producto__c = p.FS_Producto__c;
        caso.FS_Modulo__c = p.FS_Modulo__c;
        caso.FS_SubModulo__c = p.FS_SubModulo__c;
        caso.FS_DescripcionCliente__c = '<p>Test</p>';
        caso.FS_TipoIncidente__c = 'Puntual';
        caso.FS_AgenteQA__c = userInfo.getUserId();
        caso.FS_AgenteN2__c = userInfo.getUserId();
        caso.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(tipoRegistro).getRecordTypeId();
        insert caso;
        return caso;
    }
    
    public static User insertUserCommunity(Contact cont){
        User u = new User();
        u.Alias = 'tes'; 
        u.Email='test@myorg.com'; 
        u.EmailEncodingKey='UTF-8'; 
        u.LastName='Testing'; 
        u.LanguageLocaleKey='en_US'; 
        u.ContactId = cont.Id;
        u.LocaleSidKey='en_US'; 
        u.ProfileId = [Select Id from Profile Where Name = 'Customer Community User' limit 1].Id;
        u.TimeZoneSidKey='America/New_York';
        u.UserName= 'test@myorg.com';
        insert u;
        return u;
    }
        

}